# Python for Data Science Week-1 Notebook

## Table of Content

1. **[What is Python Numpy](#python_numpy)**
2. **[Functions to Create Array](#functions)**
3. **[Attributes and Functions on Array](#operations)**
4. **[Indexing Array](#Indexing)**
5. **[Slicing Array](#Slicing)**
6. **[Operations on a 1D Array](#operations_1d)**
7. **[Operations on a 2D Array](#operations_2d)**
8. **[Arithmetic Functions in Numpy](#arithmetic_functions)**
9. **[Concatenation of Array](#concatenation)**
10. **[Pandas](#pandas)**

11. **[Data Structures](#structures)**
    
12. **[Pandas Series](#series)**
    - 12.1 - [Creating a Series](#creatingS)

13. **[Pandas DataFrames](#dataframes)**
    - 13.1 - [Creating DataFrames](#creatingDF)
    - 13.2 - [Manipulating DataFrames](#manipulatingDF)

14. **[Reading Data from Different Sources](#reading_data)**

<a id="python_numpy"> </a>
### 1. What is Python Numpy

The NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc.<br>
                    It contains a powerful N-dimensional array object.<br>
                  

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [3]:
# Import numpy librabry

In [1]:
import numpy as np

#### Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Arrays occupy less memory<br>
2. work faster<br>
3. are convenient to use

#### Advantages of numpy arrays over lists

In [2]:
# create a Numpy array using arange of size 1000000
my_array = np.arange(1000000)

# create a python list using range of size 1000000
my_list = list(range(1000000))

In [3]:
# print out execution time for the following

# time required for computations in an array
%time for _ in range(10): my_modified_array = my_array ** 2

# time required for computation in an array    
%time for _ in range(10): my_modified_list = [x ** 2 for x in my_list]

CPU times: total: 46.9 ms
Wall time: 42.2 ms
CPU times: total: 1.47 s
Wall time: 1.49 s


From the above result, you can observe that the numpy arrays are faster than python lists.

Here Wall time, also called wall-clock time, measures the total time to execute a program in a computer.

<a id="functions"> </a>
### 2. Functions to Create Array

##### Create an array using np.array() function

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
type(arr)

numpy.ndarray

##### create an array from list using array() function.

In [6]:
height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
weight = [81, 55, 65, 70, 45, 44]

In [7]:
height_arr = np.array(height)
weight_arr = np.array(weight)
print('height_arr:',height_arr)
print('weight_arr:',weight_arr)
print('type of array',type(height_arr))
print('type of array',type(weight_arr))

height_arr: [5.2 5.4 4.4 4.5 5.6 6. ]
weight_arr: [81 55 65 70 45 44]
type of array <class 'numpy.ndarray'>
type of array <class 'numpy.ndarray'>


#####  Create an array using `arange()`

arange() function creates an array of numbers between the given range

In [11]:
# create an array of integers between 0 to 10  
# start: start value of interval (inclusive). 0 is the default value
# stop: stop value of interval (exclusive)
# step: returns numbers with given step_size
sequence = np.arange(start = 0, stop = 10, step = 1)

# print the sequence
sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id="operations"> </a>
### 3. Attributes and Functions on Array

#### 3.1. Attributes: 

It is defined as a specification that defines a property of an object. Attributes of the numpy array do not have parentheses following them

##### ndim:
Prints the dimension (number of axes) of the numpy array

In [12]:
arr_1 = np.array([2,3,4,5,6,7])
arr_1.ndim

1

In [13]:
arr_2 = np.array([(11,32,23),(34,55,46)])
arr_2.ndim

2

##### dtype:
Prints the data type along with the size in bytes.

In [14]:
arr_1.dtype

dtype('int64')

##### size:
Prints the number of elements in the array.



In [15]:
arr_1.size

6

##### shape
Prints the number of rows and columns of the array.

In [16]:
arr_1.shape

(6,)

In [17]:
arr_2.shape

(2, 3)

#### 3.2. Functions/method: 
A method is a function that belongs to an object. It takes parameters in the parentheses and returns the modified array. 

##### reshape:
The reshape() is used to change the number of rows and columns of an array without changing the data.<br>

<table align="center">
    <td height = '100', width = '400'>
          <img src="reshape.png">
        </td>
</table>

In [18]:
# create an array
quantity_1 = np.array([(8,9,10),(11,12,13)])
# print the array
# \n: print on a newline
print("The original array:\n", quantity_1)

# change the shape
quantity_2 = quantity_1.reshape(3,2)
# print the array
# \n: print on a newline
print("The reshaped array:\n", quantity_2)

The original array:
 [[ 8  9 10]
 [11 12 13]]
The reshaped array:
 [[ 8  9]
 [10 11]
 [12 13]]


<a id="Indexing"> </a>
### 4. Indexing Array

**Indexing in 1 dimension**

In [19]:
# declare an array
quantity = np.array([11, 22, 33, 24, 57, 473])

# print the array
print(quantity)

[ 11  22  33  24  57 473]


Each element in the array can be accessed by passing the positional index of the element.

In [20]:
# get the 1st element
# indexing starts from '0'
print(quantity[0]) 

# get the third element
print(quantity[2]) 

11
33


**Indexing in 2 dimensions**

In [21]:
# use this 2D array
quantity_2d = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])

# print the array
quantity_2d

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [22]:
# get the element in 3rd row and 2nd column

In [23]:
print(quantity_2d[2, 1])

821


<a id="Slicing"> </a>
### 5. Slicing Array

**Slicing a 1D array**

In [24]:
# declare an array
price = [101, 121, 112, 123, 114]

In [25]:
# pick the second, third, and fourth element from the array 
# indexing starts from '0' 
new_price = price[1:4]  

# print the array
new_price

[121, 112, 123]

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [26]:
# first three elements
price[:3]

[101, 121, 112]

In [27]:
# get the complete array
price[:]

[101, 121, 112, 123, 114]

**Slicing a 2D array**

In [28]:
# use this 2D array
prices_2d = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

# print the array
prices_2d

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [29]:
# select all rows except 1st

In [30]:
prices_2d[[1,2,3],:]

array([[145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [31]:
# select 3rd and 4th column

In [32]:
prices_2d[:,[2,3]]

array([[122, 113],
       [137, 318],
       [252, 253],
       [727, 928]])

**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations_1d"> </a>
### 6. Operations on a 1D Array

In [33]:
# declare two arrays
# first array
first_arr = np.array([120,230,310,410,150])

# second array
second_arr = np.arange(5)

# third array
third_arr = np.arange(4)

##### Add the two arrays

In [34]:
new_arr = first_arr + second_arr
print(new_arr)  # here the dimension is same so we can add

[120 231 312 413 154]


**Remark:** If you try to add arrays with different dimensions, you get an error.              

In [35]:
second_arr + third_arr

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [36]:
# multiply each element in the first_array by 4 

In [37]:
first_arr *4

array([ 480,  920, 1240, 1640,  600])

Use ' ** ' to compute power of the numbers.

In [38]:
# get square of each element in first_arr

In [39]:
first_arr**2

array([ 14400,  52900,  96100, 168100,  22500])

<a id="operations_2d"> </a>
### 7. Operations on a 2D Array

Let’s create 2 two-dimensional arrays, array_a and array_b.

In [46]:
# declare two arrays
# first array
quantity_A = np.array([[33,12],[70,61]])

# print the array
print("The first array is \n",quantity_A)

# second array
quantity_B  = np.array([[43,51],[72,81]])

# print the array
print("The second array is \n",quantity_B)

The first array is 
 [[33 12]
 [70 61]]
The second array is 
 [[43 51]
 [72 81]]


In [41]:
# add the 2 arrays

In [47]:
quantity_A+quantity_B

array([[ 76,  63],
       [142, 142]])

Perform multiplication on array_a and array_b.

In [48]:
# multiply the 2 arrays

In [49]:
quantity_A*quantity_B

array([[1419,  612],
       [5040, 4941]])

'+=' operation on the `quantity_A` is equivalent to adding a specified value to each element of the array. The original array gets modified using this operation.

In [50]:
# add 2 to each element

In [51]:
quantity_A + 2

array([[35, 14],
       [72, 63]])

Similarly, you can use other arithmetic operations like -= and *=

In [52]:
# subtract 2 from each element 

In [53]:
quantity_A - 2

array([[31, 10],
       [68, 59]])

In [54]:
# multiply 2 to each element 

In [55]:
quantity_A * 2

array([[ 66,  24],
       [140, 122]])

**Matrix Multiplication**<br>

Use '@' operator to perform matrix multiplication (or matrix product).

In [56]:
quantity_A @ quantity_B

array([[2283, 2655],
       [7402, 8511]])

<a id="arithmetic_functions"> </a>
### 8. Arithmetic Functions in Numpy

In [58]:
# given array
performance_scores = np.array([5,7,8,2,4])

**sum():**<br>
The sum() function adds all the values in the array and gives a scalar output.

In [59]:
np.sum(performance_scores)

np.int64(26)

**max():**<br>
The max function finds the highest value in the array.

In [60]:
np.max(performance_scores)

np.int64(8)

**min():**<br>
The min function finds the lowest value in the array.

In [61]:
np.min(performance_scores)

np.int64(2)

**mean():**<br>
The mean function finds the average value of the array.

In [62]:
np.mean(performance_scores)

np.float64(5.2)

**media():**<br>
The median function finds the median value of the array.

In [63]:
np.median(performance_scores)

np.float64(5.0)

**power():**<br>
The power function raises the numbers in the array to the given value.

In [64]:
np.power(performance_scores,2)

array([25, 49, 64,  4, 16])

**var():**<br>
The var function finds the variance of the data.

In [65]:
np.var(performance_scores)

np.float64(4.5600000000000005)

**std():**<br>
The std function finds the standard deviation of the data.

In [66]:
np.std(performance_scores)

np.float64(2.1354156504062622)

<a id="concatenation"> </a>
### 9. Concatenation of Array

The arrays can be concatenated only if they have the same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [67]:
# concatenate two 1D arrays
# production on day 1 
production_day_1 = np.array([11, 22, 13])

# production on day 2
production_day_2 = np.array([23, 22, 12])



In [68]:
# concatenate the two array giving the production for 2 days
np.concatenate([production_day_1, production_day_2])

array([11, 22, 13, 23, 22, 12])

You can also concatenate more than two arrays at once.

In [69]:
# production on day 3
production_day_3 = np.array([23,45])

In [70]:
# concatenate the two array giving the production for 3 days
total_produce = np.concatenate([production_day_1, production_day_2, production_day_3])

# print total_produce
total_produce

array([11, 22, 13, 23, 22, 12, 23, 45])

**Concatenate 2D array**

In [71]:
# create a 2D array
scores_player_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
scores_player_1

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# create a 2D array
scores_player_2 = np.array([[5, 6, 3],
                 [4, 9, 6]])
scores_player_2

array([[5, 6, 3],
       [4, 9, 6]])

**concatenate along the first axis**

In [73]:
# by default concatenate() is along 'axis = 0'
np.concatenate([scores_player_1, scores_player_2])

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 3],
       [4, 9, 6]])

**concatenate along the second axis**

In [74]:
np.concatenate([scores_player_1, scores_player_1], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Concatenate 1D and 2D array**

In [75]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'num_array_1D'
num_array_1D = np.array([23,45])

# consider a 2D array -- 'num_array_2D'
num_array_2D = np.array([[5, 6, 3],
                        [4, 9, 6]])

**Note:** One can not concatenate the arrays with different dimensions

In [76]:
np.concatenate((num_array_1D, num_array_2D), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### 10. Pandas

Pandas contain data structures and data manipulation tools designed for data cleaning and analysis.
<br><br>
                        While pandas adopt much code from NumPy, the difference is that Pandas is designed for tabular, heterogeneous data. NumPy, by difference, is best suited for working with homogeneous numerical array data.<br><br>
                         The name Pandas is derived from the term 'panel data' (an econometrics term for multidimensional structured data sets).
                

**How to install pandas?**<br>
1. You can use-<br>
`!pip install pandas`<br>
2. You can import it as 'pd'<br>
import pandas as pd

 Import the pandas library; the following convention is used

In [174]:
import pandas as pd

So from now on, we will use `pd` instead of pandas. 

### 11. Data Structures

Pandas has two data structures as follows:<br>
1. A Series is a 1-dimensional labelled array that can hold data of any type (such as integer, string, boolean, float, python objects). Its axis labels are collectively called an index.<br>
2. A DataFrame is a 2-dimensional labelled data structure with columns. It supports multiple data types.

### 12. Pandas Series

Pandas Series is a one-dimensional labelled array capable of holding any data type. However, a series is a sequence of similar data types, similar to an array, list, or column in a table. <br><Br>It will assign a labelled index to each item in the pd.Series. By default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.

### 12.1 Creating a Series

##### 1. To create a numeric series

In [173]:
# create a numeric series
numbers = range(1,100,5)

In [175]:
# covert it to series
pd.Series(numbers)

0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

The output also gives the data type of the series as `int64`

Furthermore,  note that by default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.

<b>In python, the row names are called index.</b>

**2. To create an object series** 

In [176]:
# create an object series
string = ["Hi" , "How" ,"are", "you", "?"]
# create a series from the above list
pd.Series(string)

0     Hi
1    How
2    are
3    you
4      ?
dtype: object

The output gives the data type of the series as `object`

**3. To create a series by giving both numeric and string values** 

In [177]:
# create a Series with an arbitrary list
pd.Series([345, 'London', 34.5, -34.45, 'Happy Birthday'])

0               345
1            London
2              34.5
3            -34.45
4    Happy Birthday
dtype: object

Here the numeric values are treated as object.

**4. To set index values for a series**

In [178]:
# declare a list of marks
marks = [60, 89, 74, 86]

# declare a list of subjects
subject = ["Maths", "Science", "English" , "Social Science"]

# create a series from the above list of marks with subjects as its index names
# index: adds the index 
marks_series = pd.Series(marks, index = subject) 
marks_series

Maths             60
Science           89
English           74
Social Science    86
dtype: int64

The index is added using the argument `index=`. The data type of the series continues to be numeric.

**5. To print the values and index of the Series**

In [180]:
# print the index of the series
marks_series.index

Index(['Maths', 'Science', 'English', 'Social Science'], dtype='object')

In [183]:
# prints the values of the series
marks_series.values

array([60, 89, 74, 86])

### 13. Pandas DataFrames

 A DataFrame is a tabular representation of data containing an ordered collection of columns, each of which can be a different type (such as numeric, string, boolean). <br><br>
                        The DataFrame has both row and column index; it can be thought of as a dict of Series all sharing the same index. In a data frame, the data is stored as one or more two-dimensional blocks rather than a list, dict, or some other collection of one-dimensional arrays. <br><br>
                        While a DataFrame is physically two-dimensional, it can be used to represent higher dimensional data in a tabular format using hierarchical indexing.
                   

### 13.1 Creating DataFrames

#####  Creating a data frame a dictionary

In [189]:
# create a dictionary
data = {'Subject': ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'],
        'Marks': (45, 65, 78, 65, 80, 78),
        'GPA': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}


In [191]:
df = pd.DataFrame(data)
df

,Subject,Marks,GPA
0,Maths,45,2.5
1,History,65,3.0
2,Science,78,3.5
3,English,65,2.0
4,Georaphy,80,4.0
5,Art,78,4.0


**Note:** Like Series, the resulting DataFrame is assigned index automatically. And the 'Marks' values are in a tuple. 

#####  To create dataframe from lists

In [193]:
# declare the list 'Subject'
Subject = ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art']

# declare the list 'Marks'
Marks = [45, 65, 78, 65, 80, 78]

# declare the list 'CPA'
GPA = [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]

In [197]:
# create a DataFrame from the lists
# index: specifies the index names
df_marks = pd.DataFrame([Subject, Marks, GPA], index = ['Subject','Marks','GPA'])

# print the DataFrame
df_marks

,0,1,2,3,4,5
Subject,Maths,History,Science,English,Georaphy,Art
Marks,45,65,78,65,80,78
GPA,2.5,3.0,3.5,2.0,4.0,4.0


However to want a vertical dataframe so we use `.T`. The 'T' stands for transpose.

In [199]:
# transpose the DataFrame
df_marks.T

,Subject,Marks,GPA
0,Maths,45,2.5
1,History,65,3.0
2,Science,78,3.5
3,English,65,2.0
4,Georaphy,80,4.0
5,Art,78,4.0


#####  To create dataframe from series

In [200]:
# declare the series 'Subject'
Subject = pd.Series(['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'])

# declare the series 'Marks'
Marks = pd.Series([45, 65, 78, 65, 80, 78])

# declare the series 'GPA'
GPA = pd.Series([2.5, 3.0, 3.5, 2.0, 4.0, 4.0])

In [201]:
# create a DataFrame from the Series
# index: specifies the index names
df_marks = pd.DataFrame([Subject, Marks, GPA], index = ['Subject','Marks','GPA'])

# print the DataFrame
df_marks

,0,1,2,3,4,5
Subject,Maths,History,Science,English,Georaphy,Art
Marks,45,65,78,65,80,78
GPA,2.5,3.0,3.5,2.0,4.0,4.0


However to want a vertical dataframe so we use `.T`. The 'T' stands for transpose.

In [203]:
# transpose the DataFrame
df_marks.T

,Subject,Marks,GPA
0,Maths,45,2.5
1,History,65,3.0
2,Science,78,3.5
3,English,65,2.0
4,Georaphy,80,4.0
5,Art,78,4.0


In [256]:
Salaries =pd.DataFrame(
    {
    'designation': [
        'Senior Manager', 'Manager', 'Associate', 'Manager', 'Associate', 'Senior Manager',
        'Associate', 'Manager', 'Senior Manager', 'Associate',
        'Manager', 'Manager', 'Senior Manager', 'Associate', 'Manager',
        'Senior Manager', 'Associate', 'Manager', 'Senior Manager', 'Associate',
        'Manager', 'Senior Manager', 'Associate', 'Manager', 'Associate',
        'Senior Manager', 'Manager', 'Associate', 'Senior Manager', 'Associate'
    ],
    'salary': [
        180000, 95000, 45000, 88000, 52000, 170000,
        48000, 100000, 160000, 46000,
        92000, 97000, 185000, 55000, 89000,
        175000, 49000, 93000, 168000, 50000,
        91000, 162000, 47000, 88000, 53000,
        190000, 94000, 56000, 172000, 51000
    ],
    'gender': [
        'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
        'Other', 'Female', 'Male', 'Female',
        'Male', 'Female', 'Male', 'Other', 'Female',
        'Male', 'Male', 'Female', 'Female', 'Male',
        'Female', 'Male', 'Other', 'Male', 'Female',
        'Female', 'Male', 'Female', 'Male', 'Female'
    ],
    'experience': [
        18, 10, 3, 9, 2, 17,
        4, 11, 16, 3,
        10, 12, 19, 5, 9,
        18, 4, 11, 15, 3,
        10, 16, 5, 9, 2,
        20, 11, 4, 17, 3
    ],
    'age': [
        52, 38, 25, 36, 24, 55,
        27, 40, 50, 23,
        35, 42, 57, 28, 39,
        54, 26, 37, 48, 25,
        34, 49, 29, 33, 24,
        58, 41, 27, 53, 26
    ]
})
Salaries

,designation,salary,gender,experience,age
0,Senior Manager,180000,Male,18,52
1,Manager,95000,Female,10,38
2,Associate,45000,Female,3,25
3,Manager,88000,Male,9,36
4,Associate,52000,Male,2,24
5,Senior Manager,170000,Female,17,55
6,Associate,48000,Other,4,27
7,Manager,100000,Female,11,40
8,Senior Manager,160000,Male,16,50
9,Associate,46000,Female,3,23


#####  To print head of the data

In [211]:
Salaries.head()

,designation,salary,gender,experience,age
0,Senior Manager,180000,Male,18,52
1,Manager,95000,Female,10,38
2,Associate,45000,Female,3,25
3,Manager,88000,Male,9,36
4,Associate,52000,Male,2,24


#####  To print tail of the data

In [212]:
Salaries.tail()

,designation,salary,gender,experience,age
25,Senior Manager,190000,Female,20,58
26,Manager,94000,Male,11,41
27,Associate,56000,Female,4,27
28,Senior Manager,172000,Male,17,53
29,Associate,51000,Female,3,26


#####  To obtain the dimension of the data

In [213]:
Salaries.shape

(30, 5)

#####  To know some information of the data

In [218]:
Salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   designation  30 non-null     object
 1   salary       30 non-null     int64 
 2   gender       30 non-null     object
 3   experience   30 non-null     int64 
 4   age          30 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 1.3+ KB


#####  To check the data type of column in the data frame

In [220]:
Salaries.dtypes

designation    object
salary          int64
gender         object
experience      int64
age             int64
dtype: object

##### To check the data structure of column in data frame

In [223]:
type(Salaries['designation'])

pandas.core.series.Series

### 13.2  Manipulating DataFrames 

#####  Adding a new column to the data set

In [258]:
Salaries['Emp_ID'] = range(100,130)

In [229]:
Salaries.head()

,designation,salary,gender,experience,age,Emp_ID
0,Senior Manager,180000,Male,18,52,100
1,Manager,95000,Female,10,38,101
2,Associate,45000,Female,3,25,102
3,Manager,88000,Male,9,36,103
4,Associate,52000,Male,2,24,104


####  1.Indexing a dataframe using `.loc`

`DataFrame.loc[]` method is a method that takes only index labels and returns row or dataframe if the index label exists in the caller data frame. <br>
`DataFrame.loc[Row_names, column_names]` is used to select or index rows or columns based on their name.

###### Select 1 to 5 rows and salary,gender columns

In [237]:
Salaries.loc[0:5,['salary','gender']]

,salary,gender
0,180000,Male
1,95000,Female
2,45000,Female
3,88000,Male
4,52000,Male
5,170000,Female


###### select 3rd row and designation,salary

In [238]:
Salaries.loc[2,['designation','salary']]

designation    Associate
salary             45000
Name: 2, dtype: object

###### select all rows of designation,salary&age column

In [270]:
Salaries.loc[:,['designation','salary','age']]

In [287]:
#This can be directly written like this too.
Salaries[['designation','salary','age']] # if we are selecting all the rows than we can directly write the code like this.

,designation,salary,age
0,Senior Manager,180000,52
1,Manager,95000,38
2,Associate,45000,25
3,Manager,88000,36
4,Associate,52000,24
5,Senior Manager,170000,55
6,Associate,48000,27
7,Manager,100000,40
8,Senior Manager,160000,50
9,Associate,46000,23


###### Add a new row to the data set

A new row can be added using the `loc`

In [241]:
Salaries.loc[30] = ['Associate', 32000, 'Male',9,31,'130']

In [243]:
Salaries.loc[30]

designation    Associate
salary             32000
gender              Male
experience             9
age                   31
Emp_ID               130
Name: 30, dtype: object

### Understanding loc by resetting Salaries dataframe index

In [259]:
Salaries_reset = Salaries.set_index('Emp_ID')

In [271]:
Salaries_reset.head()

,designation,salary,gender,experience,age
Emp_ID,,,,,
100,Senior Manager,180000,Male,18,52
101,Manager,95000,Female,10,38
102,Associate,45000,Female,3,25
103,Manager,88000,Male,9,36
104,Associate,52000,Male,2,24


In [272]:
### Find the gender and salary details of emp_id 109,110,112

In [269]:
Salaries_reset.loc[[109,110,112],['gender','salary']]

,gender,salary
Emp_ID,,
109,Female,46000
110,Male,92000
112,Male,185000


####  2.Indexing a dataframe using `.iloc`

`DataFrame.iloc[]` method is used when the index label of a data frame is something other than numeric series of 0, 1, 2, 3….n or in case the user doesn’t know the index label. 

In [280]:
# Here in the Salaries_reset data where the index in emp_id and if we try to index the data using default 
# python indexing 0,1,2...n this will throw an error so we use iloc.
#Salaries_reset.loc[0] (uncomment and run this cell you will get error)

In [278]:
Salaries_reset.loc[100]

designation    Senior Manager
salary                 180000
gender                   Male
experience                 18
age                        52
Name: 100, dtype: object

In [279]:
Salaries_reset.iloc[0]

designation    Senior Manager
salary                 180000
gender                   Male
experience                 18
age                        52
Name: 100, dtype: object

###### Select fourth, seventh and tenth rows

In [281]:
Salaries_reset.iloc[[3,6,9],:]

,designation,salary,gender,experience,age
Emp_ID,,,,,
103,Manager,88000,Male,9,36
106,Associate,48000,Other,4,27
109,Associate,46000,Female,3,23


###### Select 12th to 17th rows

In [282]:
Salaries_reset.iloc[[13,18],:]

,designation,salary,gender,experience,age
Emp_ID,,,,,
113,Associate,55000,Other,5,28
118,Senior Manager,168000,Female,15,48


###### Select the 1st column

In [284]:
Salaries_reset.iloc[:,[0]]

,designation
Emp_ID,
100,Senior Manager
101,Manager
102,Associate
103,Manager
104,Associate
105,Senior Manager
106,Associate
107,Manager
108,Senior Manager


###### Select the last column

In [286]:
Salaries_reset.iloc[:,[4]]

,age
Emp_ID,
100,52
101,38
102,25
103,36
104,24
105,55
106,27
107,40
108,50


##### 3. Conditional subsetting

In [292]:
Salaries.head(1)

,designation,salary,gender,experience,age,Emp_ID
0,Senior Manager,180000,Male,18,52,100


##### Selecting rows where the value of `age` is greater than 47 

In [296]:
Salaries['age']>47  # this will give boolean output 

0      True
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16    False
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24    False
25     True
26    False
27    False
28     True
29    False
Name: age, dtype: bool

In [298]:
Salaries[Salaries['age']>47]

,designation,salary,gender,experience,age,Emp_ID
0,Senior Manager,180000,Male,18,52,100
5,Senior Manager,170000,Female,17,55,105
8,Senior Manager,160000,Male,16,50,108
12,Senior Manager,185000,Male,19,57,112
15,Senior Manager,175000,Male,18,54,115
18,Senior Manager,168000,Female,15,48,118
21,Senior Manager,162000,Male,16,49,121
25,Senior Manager,190000,Female,20,58,125
28,Senior Manager,172000,Male,17,53,128


##### Subsetting the age more than 55 *or* salary column value more than 189000

In [305]:
Salaries[ (Salaries['age']>55) | (Salaries['salary']>189000)]

,designation,salary,gender,experience,age,Emp_ID
12,Senior Manager,185000,Male,19,57,112
25,Senior Manager,190000,Female,20,58,125


##### Subsetting the age more than 55 *and* salary column value more than 189000

In [306]:
Salaries[ (Salaries['age']>55) & (Salaries['salary']>189000)]

,designation,salary,gender,experience,age,Emp_ID
25,Senior Manager,190000,Female,20,58,125


#### 4. Sort the data frame on the basis of values in a column

In [309]:
Salaries.sort_values('salary') # default Ascending order small to high

,designation,salary,gender,experience,age,Emp_ID
2,Associate,45000,Female,3,25,102
9,Associate,46000,Female,3,23,109
22,Associate,47000,Other,5,29,122
6,Associate,48000,Other,4,27,106
16,Associate,49000,Male,4,26,116
19,Associate,50000,Male,3,25,119
29,Associate,51000,Female,3,26,129
4,Associate,52000,Male,2,24,104
24,Associate,53000,Female,2,24,124
13,Associate,55000,Other,5,28,113


In [311]:
Salaries.sort_values('salary',ascending=False) # Ascending=False means descending order will be considered order high to small

,designation,salary,gender,experience,age,Emp_ID
25,Senior Manager,190000,Female,20,58,125
12,Senior Manager,185000,Male,19,57,112
0,Senior Manager,180000,Male,18,52,100
15,Senior Manager,175000,Male,18,54,115
28,Senior Manager,172000,Male,17,53,128
5,Senior Manager,170000,Female,17,55,105
18,Senior Manager,168000,Female,15,48,118
21,Senior Manager,162000,Male,16,49,121
8,Senior Manager,160000,Male,16,50,108
7,Manager,100000,Female,11,40,107


##### 5. Rank the dataframe

In [327]:
marks = pd.DataFrame({'Name':['Hari','Mike','Cena','Lyon','Veeru','Vian','Mani','Gopal','Misty','Loki'],'Scores':[45,65,65,76,76,87,89,91,98,99]})

In [328]:
marks['Rank_min'] = marks['Scores'].rank(method  = 'min')
marks['Rank_max'] = marks['Scores'].rank(method  = 'max')
marks['Rank_first'] = marks['Scores'].rank(method  = 'first')
marks['Rank_average'] = marks['Scores'].rank(method  = 'average')
marks['Rank_dense'] = marks['Scores'].rank(method  = 'dense')

In [329]:
marks

,Name,Scores,Rank_min,Rank_max,Rank_first,Rank_average,Rank_dense
0,Hari,45,1.0,1.0,1.0,1.0,1.0
1,Mike,65,2.0,3.0,2.0,2.5,2.0
2,Cena,65,2.0,3.0,3.0,2.5,2.0
3,Lyon,76,4.0,5.0,4.0,4.5,3.0
4,Veeru,76,4.0,5.0,5.0,4.5,3.0
5,Vian,87,6.0,6.0,6.0,6.0,4.0
6,Mani,89,7.0,7.0,7.0,7.0,5.0
7,Gopal,91,8.0,8.0,8.0,8.0,6.0
8,Misty,98,9.0,9.0,9.0,9.0,7.0
9,Loki,99,10.0,10.0,10.0,10.0,8.0


##### 6. To check for missing values

We shall import a new dataset.

In [339]:
basic_info.isnull()

,Age,Weight (in kg),Height (in m)
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False
4,False,False,False
5,False,True,False
6,False,False,False
7,False,False,False
8,False,False,False
9,False,False,False


In [340]:
basic_info.isnull().sum()

Age               1
Weight (in kg)    2
Height (in m)     1
dtype: int64

The function `.isnull` check whether the data is missing. The `sum()` sums the number of 'True' values in the column. The final output gives the number of missing values in each column.

<a id="reading_data"> </a>
### 16.  Reading Data from Different Sources

##### Read a CSV file

In [332]:
basic_info = pd.read_csv('basic_info.csv')

##### Read a `.xlsx` file

In [333]:
employees_info = pd.read_excel('employee_info.xlsx')

##### Read data from Seaborn library.

In [334]:
import seaborn as sns 

In [335]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [337]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
